version: '3.0'
services:
  mysql8:
    image: mysql:8.0
    container_name: geekweb-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"

  redis:
    image: bitnami/redis:latest
    container_name: geekweb-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'
