// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"geekweb/geek"
	"geekweb/internal/repository"
	"geekweb/internal/repository/cache"
	"geekweb/internal/repository/dao"
	"geekweb/internal/service"
	"geekweb/internal/web"
	"geekweb/ioc"
)

// Injectors from wire.go:

func initWebServer() *geek.HTTPServer {
	v := ioc.InitMiddlewares()
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitCache()
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService)
	httpServer := ioc.InitWebServer(v, userHandler)
	return httpServer
}
